FROM nginx

WORKDIR /home/

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./mini_server.c /home/
COPY ./build_server.sh /home/

RUN chmod +x build_server.sh \
    && apt-get update \
    && apt-get install -y gcc spawn-fcgi libfcgi-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/home/build_server.sh"]